// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: wxbase/v1/wx_base.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReceiveWxMessageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XmlData string `protobuf:"bytes,1,opt,name=xml_data,json=xmlData,proto3" json:"xml_data,omitempty"`
}

func (x *ReceiveWxMessageRequest) Reset() {
	*x = ReceiveWxMessageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveWxMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveWxMessageRequest) ProtoMessage() {}

func (x *ReceiveWxMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveWxMessageRequest.ProtoReflect.Descriptor instead.
func (*ReceiveWxMessageRequest) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{0}
}

func (x *ReceiveWxMessageRequest) GetXmlData() string {
	if x != nil {
		return x.XmlData
	}
	return ""
}

type ReceiveWxMessageReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReceiveWxMessageReply) Reset() {
	*x = ReceiveWxMessageReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveWxMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveWxMessageReply) ProtoMessage() {}

func (x *ReceiveWxMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveWxMessageReply.ProtoReflect.Descriptor instead.
func (*ReceiveWxMessageReply) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{1}
}

type WxCallbackRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature string `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Timestamp string `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce     string `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Echostr   string `protobuf:"bytes,4,opt,name=echostr,proto3" json:"echostr,omitempty"`
}

func (x *WxCallbackRequest) Reset() {
	*x = WxCallbackRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxCallbackRequest) ProtoMessage() {}

func (x *WxCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxCallbackRequest.ProtoReflect.Descriptor instead.
func (*WxCallbackRequest) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{2}
}

func (x *WxCallbackRequest) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *WxCallbackRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *WxCallbackRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *WxCallbackRequest) GetEchostr() string {
	if x != nil {
		return x.Echostr
	}
	return ""
}

type WxCallbackReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Echostr string `protobuf:"bytes,1,opt,name=echostr,proto3" json:"echostr,omitempty"`
}

func (x *WxCallbackReply) Reset() {
	*x = WxCallbackReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WxCallbackReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WxCallbackReply) ProtoMessage() {}

func (x *WxCallbackReply) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WxCallbackReply.ProtoReflect.Descriptor instead.
func (*WxCallbackReply) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{3}
}

func (x *WxCallbackReply) GetEchostr() string {
	if x != nil {
		return x.Echostr
	}
	return ""
}

// GetOpenidByCode 方法
// 通过code获取openid
// customer和appId：二选一
type GetOpenidByCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Customer string `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"` // 小程序名称
	AppId    string `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`       // 小程序appId
	Code     string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`         // 微信侧获取的用户code
}

func (x *GetOpenidByCodeRequest) Reset() {
	*x = GetOpenidByCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOpenidByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenidByCodeRequest) ProtoMessage() {}

func (x *GetOpenidByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenidByCodeRequest.ProtoReflect.Descriptor instead.
func (*GetOpenidByCodeRequest) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{4}
}

func (x *GetOpenidByCodeRequest) GetCustomer() string {
	if x != nil {
		return x.Customer
	}
	return ""
}

func (x *GetOpenidByCodeRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetOpenidByCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetOpenidByCodeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret  int32                      `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Msg  string                     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *GetOpenidByCodeReply_Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetOpenidByCodeReply) Reset() {
	*x = GetOpenidByCodeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOpenidByCodeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenidByCodeReply) ProtoMessage() {}

func (x *GetOpenidByCodeReply) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenidByCodeReply.ProtoReflect.Descriptor instead.
func (*GetOpenidByCodeReply) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{5}
}

func (x *GetOpenidByCodeReply) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GetOpenidByCodeReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetOpenidByCodeReply) GetData() *GetOpenidByCodeReply_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// AddOfficialAccount 方法
// 添加公众号
type AddOfficialAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name           string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                     // 公众号名称
	AppId          string `protobuf:"bytes,2,opt,name=appId,proto3" json:"appId,omitempty"`                   // 公众号appId
	AppSecret      string `protobuf:"bytes,3,opt,name=appSecret,proto3" json:"appSecret,omitempty"`           // 公众号appSecret
	Token          string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`                   // 公众号token
	EncodingAesKey string `protobuf:"bytes,5,opt,name=encodingAesKey,proto3" json:"encodingAesKey,omitempty"` // 公众号encodingAesKey
	TokenUrl       string `protobuf:"bytes,6,opt,name=tokenUrl,proto3" json:"tokenUrl,omitempty"`             // 公众号tokenUrl
	AppIdAlias     string `protobuf:"bytes,7,opt,name=appIdAlias,proto3" json:"appIdAlias,omitempty"`         // 公众号appId别名
}

func (x *AddOfficialAccountRequest) Reset() {
	*x = AddOfficialAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOfficialAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOfficialAccountRequest) ProtoMessage() {}

func (x *AddOfficialAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOfficialAccountRequest.ProtoReflect.Descriptor instead.
func (*AddOfficialAccountRequest) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{6}
}

func (x *AddOfficialAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddOfficialAccountRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *AddOfficialAccountRequest) GetAppSecret() string {
	if x != nil {
		return x.AppSecret
	}
	return ""
}

func (x *AddOfficialAccountRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AddOfficialAccountRequest) GetEncodingAesKey() string {
	if x != nil {
		return x.EncodingAesKey
	}
	return ""
}

func (x *AddOfficialAccountRequest) GetTokenUrl() string {
	if x != nil {
		return x.TokenUrl
	}
	return ""
}

func (x *AddOfficialAccountRequest) GetAppIdAlias() string {
	if x != nil {
		return x.AppIdAlias
	}
	return ""
}

type AddOfficialAccountReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 公众号名称
	Id   int64  `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`    // id
}

func (x *AddOfficialAccountReply) Reset() {
	*x = AddOfficialAccountReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddOfficialAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOfficialAccountReply) ProtoMessage() {}

func (x *AddOfficialAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOfficialAccountReply.ProtoReflect.Descriptor instead.
func (*AddOfficialAccountReply) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{7}
}

func (x *AddOfficialAccountReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddOfficialAccountReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// AddMiniProgram 方法
// 添加小程序
type AddMiniProgramRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddMiniProgramRequest) Reset() {
	*x = AddMiniProgramRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMiniProgramRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMiniProgramRequest) ProtoMessage() {}

func (x *AddMiniProgramRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMiniProgramRequest.ProtoReflect.Descriptor instead.
func (*AddMiniProgramRequest) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{8}
}

type AddMiniProgramReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddMiniProgramReply) Reset() {
	*x = AddMiniProgramReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddMiniProgramReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMiniProgramReply) ProtoMessage() {}

func (x *AddMiniProgramReply) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMiniProgramReply.ProtoReflect.Descriptor instead.
func (*AddMiniProgramReply) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{9}
}

// UpdateOfficialAccount 方法
// 修改公众号
type UpdateOfficialAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateOfficialAccountRequest) Reset() {
	*x = UpdateOfficialAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOfficialAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOfficialAccountRequest) ProtoMessage() {}

func (x *UpdateOfficialAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOfficialAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateOfficialAccountRequest) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{10}
}

type UpdateOfficialAccountReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateOfficialAccountReply) Reset() {
	*x = UpdateOfficialAccountReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOfficialAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOfficialAccountReply) ProtoMessage() {}

func (x *UpdateOfficialAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOfficialAccountReply.ProtoReflect.Descriptor instead.
func (*UpdateOfficialAccountReply) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{11}
}

// DeleteOfficialAccount 方法
// 删除公众号
type DeleteOfficialAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteOfficialAccountRequest) Reset() {
	*x = DeleteOfficialAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOfficialAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOfficialAccountRequest) ProtoMessage() {}

func (x *DeleteOfficialAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOfficialAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteOfficialAccountRequest) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{12}
}

type DeleteOfficialAccountReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteOfficialAccountReply) Reset() {
	*x = DeleteOfficialAccountReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteOfficialAccountReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOfficialAccountReply) ProtoMessage() {}

func (x *DeleteOfficialAccountReply) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOfficialAccountReply.ProtoReflect.Descriptor instead.
func (*DeleteOfficialAccountReply) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{13}
}

// GetOfficialAccountList 方法
// 获取公众号列表
type GetOfficialAccountListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetOfficialAccountListRequest) Reset() {
	*x = GetOfficialAccountListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOfficialAccountListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfficialAccountListRequest) ProtoMessage() {}

func (x *GetOfficialAccountListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfficialAccountListRequest.ProtoReflect.Descriptor instead.
func (*GetOfficialAccountListRequest) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{14}
}

type GetOfficialAccountListReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetOfficialAccountListReply) Reset() {
	*x = GetOfficialAccountListReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOfficialAccountListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOfficialAccountListReply) ProtoMessage() {}

func (x *GetOfficialAccountListReply) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOfficialAccountListReply.ProtoReflect.Descriptor instead.
func (*GetOfficialAccountListReply) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{15}
}

type GetOpenidByCodeReply_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Openid string `protobuf:"bytes,1,opt,name=openid,proto3" json:"openid,omitempty"`
	Mobile string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"` // 如果绑定过，mobile才会有值
}

func (x *GetOpenidByCodeReply_Data) Reset() {
	*x = GetOpenidByCodeReply_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_wxbase_v1_wx_base_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOpenidByCodeReply_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenidByCodeReply_Data) ProtoMessage() {}

func (x *GetOpenidByCodeReply_Data) ProtoReflect() protoreflect.Message {
	mi := &file_wxbase_v1_wx_base_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenidByCodeReply_Data.ProtoReflect.Descriptor instead.
func (*GetOpenidByCodeReply_Data) Descriptor() ([]byte, []int) {
	return file_wxbase_v1_wx_base_proto_rawDescGZIP(), []int{5, 0}
}

func (x *GetOpenidByCodeReply_Data) GetOpenid() string {
	if x != nil {
		return x.Openid
	}
	return ""
}

func (x *GetOpenidByCodeReply_Data) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

var File_wxbase_v1_wx_base_proto protoreflect.FileDescriptor

var file_wxbase_v1_wx_base_proto_rawDesc = []byte{
	0x0a, 0x17, 0x77, 0x78, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x77, 0x78, 0x5f, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x17, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x57, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x78, 0x6d, 0x6c, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x78, 0x6d, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x22, 0x17, 0x0a, 0x15,
	0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x57, 0x78, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x7f, 0x0a, 0x11, 0x57, 0x78, 0x43, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x65, 0x63, 0x68, 0x6f, 0x73, 0x74, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65,
	0x63, 0x68, 0x6f, 0x73, 0x74, 0x72, 0x22, 0x2b, 0x0a, 0x0f, 0x57, 0x78, 0x43, 0x61, 0x6c, 0x6c,
	0x62, 0x61, 0x63, 0x6b, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x63, 0x68,
	0x6f, 0x73, 0x74, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x63, 0x68, 0x6f,
	0x73, 0x74, 0x72, 0x22, 0x5e, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x64,
	0x42, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0xb0, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x69,
	0x64, 0x42, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x12, 0x3c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x42, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x36,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x22, 0xdd, 0x01, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x4f, 0x66,
	0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x61, 0x70, 0x70, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x61, 0x70, 0x70, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x65,
	0x73, 0x4b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x65, 0x6e, 0x63, 0x6f,
	0x64, 0x69, 0x6e, 0x67, 0x41, 0x65, 0x73, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x55, 0x72, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x70, 0x70, 0x49, 0x64, 0x41,
	0x6c, 0x69, 0x61, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x49,
	0x64, 0x41, 0x6c, 0x69, 0x61, 0x73, 0x22, 0x3d, 0x0a, 0x17, 0x41, 0x64, 0x64, 0x4f, 0x66, 0x66,
	0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x4d, 0x69, 0x6e, 0x69,
	0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x15,
	0x0a, 0x13, 0x41, 0x64, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1e, 0x0a, 0x1c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f,
	0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f,
	0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x1e, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x66, 0x66,
	0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x66, 0x66,
	0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x1f, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x1d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61,
	0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x32, 0xb2, 0x05, 0x0a, 0x0f, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x5f, 0x0a, 0x0a, 0x57, 0x78, 0x43, 0x61, 0x6c, 0x6c, 0x62,
	0x61, 0x63, 0x6b, 0x12, 0x20, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2e, 0x76, 0x31, 0x2e, 0x57, 0x78, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72,
	0x6c, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x78, 0x43, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63, 0x6b,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x09, 0x12, 0x07, 0x2f,
	0x77, 0x78, 0x2f, 0x6e, 0x65, 0x77, 0x12, 0x87, 0x01, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x4f, 0x66,
	0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x2e,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64,
	0x64, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x4f, 0x66, 0x66, 0x69, 0x63,
	0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x3a, 0x01, 0x2a, 0x22, 0x14, 0x2f, 0x76, 0x31, 0x2f,
	0x6f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x90, 0x01, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x69, 0x63,
	0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2b, 0x2e, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x66,
	0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x1f, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x19, 0x3a, 0x01, 0x2a, 0x1a, 0x14, 0x2f,
	0x76, 0x31, 0x2f, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x8d, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4f, 0x66,
	0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2b, 0x2e,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x29, 0x2e, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x2a, 0x14, 0x2f,
	0x76, 0x31, 0x2f, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x90, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4f, 0x66, 0x66, 0x69, 0x63,
	0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2c,
	0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16,
	0x12, 0x14, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xfc, 0x01, 0x0a, 0x0b, 0x4d, 0x69, 0x6e, 0x69, 0x50,
	0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x74, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65,
	0x6e, 0x69, 0x64, 0x42, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x2e, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65,
	0x6e, 0x69, 0x64, 0x42, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x42, 0x79, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f,
	0x76, 0x31, 0x2f, 0x77, 0x78, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x64, 0x12, 0x77, 0x0a, 0x0e,
	0x41, 0x64, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x12, 0x24,
	0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2e, 0x76, 0x31, 0x2e, 0x41,
	0x64, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x61, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x64, 0x4d, 0x69, 0x6e, 0x69, 0x50, 0x72, 0x6f, 0x67,
	0x72, 0x61, 0x6d, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15,
	0x3a, 0x01, 0x2a, 0x22, 0x10, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x69, 0x6e, 0x69, 0x5f, 0x70, 0x72,
	0x6f, 0x67, 0x72, 0x61, 0x6d, 0x42, 0x1b, 0x5a, 0x19, 0x77, 0x78, 0x2d, 0x62, 0x61, 0x73, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x77, 0x78, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x2f, 0x76, 0x31, 0x3b,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_wxbase_v1_wx_base_proto_rawDescOnce sync.Once
	file_wxbase_v1_wx_base_proto_rawDescData = file_wxbase_v1_wx_base_proto_rawDesc
)

func file_wxbase_v1_wx_base_proto_rawDescGZIP() []byte {
	file_wxbase_v1_wx_base_proto_rawDescOnce.Do(func() {
		file_wxbase_v1_wx_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_wxbase_v1_wx_base_proto_rawDescData)
	})
	return file_wxbase_v1_wx_base_proto_rawDescData
}

var file_wxbase_v1_wx_base_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_wxbase_v1_wx_base_proto_goTypes = []interface{}{
	(*ReceiveWxMessageRequest)(nil),       // 0: helloworld.v1.ReceiveWxMessageRequest
	(*ReceiveWxMessageReply)(nil),         // 1: helloworld.v1.ReceiveWxMessageReply
	(*WxCallbackRequest)(nil),             // 2: helloworld.v1.WxCallbackRequest
	(*WxCallbackReply)(nil),               // 3: helloworld.v1.WxCallbackReply
	(*GetOpenidByCodeRequest)(nil),        // 4: helloworld.v1.GetOpenidByCodeRequest
	(*GetOpenidByCodeReply)(nil),          // 5: helloworld.v1.GetOpenidByCodeReply
	(*AddOfficialAccountRequest)(nil),     // 6: helloworld.v1.AddOfficialAccountRequest
	(*AddOfficialAccountReply)(nil),       // 7: helloworld.v1.AddOfficialAccountReply
	(*AddMiniProgramRequest)(nil),         // 8: helloworld.v1.AddMiniProgramRequest
	(*AddMiniProgramReply)(nil),           // 9: helloworld.v1.AddMiniProgramReply
	(*UpdateOfficialAccountRequest)(nil),  // 10: helloworld.v1.UpdateOfficialAccountRequest
	(*UpdateOfficialAccountReply)(nil),    // 11: helloworld.v1.UpdateOfficialAccountReply
	(*DeleteOfficialAccountRequest)(nil),  // 12: helloworld.v1.DeleteOfficialAccountRequest
	(*DeleteOfficialAccountReply)(nil),    // 13: helloworld.v1.DeleteOfficialAccountReply
	(*GetOfficialAccountListRequest)(nil), // 14: helloworld.v1.GetOfficialAccountListRequest
	(*GetOfficialAccountListReply)(nil),   // 15: helloworld.v1.GetOfficialAccountListReply
	(*GetOpenidByCodeReply_Data)(nil),     // 16: helloworld.v1.GetOpenidByCodeReply.Data
}
var file_wxbase_v1_wx_base_proto_depIdxs = []int32{
	16, // 0: helloworld.v1.GetOpenidByCodeReply.data:type_name -> helloworld.v1.GetOpenidByCodeReply.Data
	2,  // 1: helloworld.v1.OfficialAccount.WxCallback:input_type -> helloworld.v1.WxCallbackRequest
	6,  // 2: helloworld.v1.OfficialAccount.AddOfficialAccount:input_type -> helloworld.v1.AddOfficialAccountRequest
	10, // 3: helloworld.v1.OfficialAccount.UpdateOfficialAccount:input_type -> helloworld.v1.UpdateOfficialAccountRequest
	12, // 4: helloworld.v1.OfficialAccount.DeleteOfficialAccount:input_type -> helloworld.v1.DeleteOfficialAccountRequest
	14, // 5: helloworld.v1.OfficialAccount.GetOfficialAccountList:input_type -> helloworld.v1.GetOfficialAccountListRequest
	4,  // 6: helloworld.v1.MiniProgram.GetOpenidByCode:input_type -> helloworld.v1.GetOpenidByCodeRequest
	8,  // 7: helloworld.v1.MiniProgram.AddMiniProgram:input_type -> helloworld.v1.AddMiniProgramRequest
	3,  // 8: helloworld.v1.OfficialAccount.WxCallback:output_type -> helloworld.v1.WxCallbackReply
	7,  // 9: helloworld.v1.OfficialAccount.AddOfficialAccount:output_type -> helloworld.v1.AddOfficialAccountReply
	11, // 10: helloworld.v1.OfficialAccount.UpdateOfficialAccount:output_type -> helloworld.v1.UpdateOfficialAccountReply
	13, // 11: helloworld.v1.OfficialAccount.DeleteOfficialAccount:output_type -> helloworld.v1.DeleteOfficialAccountReply
	15, // 12: helloworld.v1.OfficialAccount.GetOfficialAccountList:output_type -> helloworld.v1.GetOfficialAccountListReply
	5,  // 13: helloworld.v1.MiniProgram.GetOpenidByCode:output_type -> helloworld.v1.GetOpenidByCodeReply
	9,  // 14: helloworld.v1.MiniProgram.AddMiniProgram:output_type -> helloworld.v1.AddMiniProgramReply
	8,  // [8:15] is the sub-list for method output_type
	1,  // [1:8] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_wxbase_v1_wx_base_proto_init() }
func file_wxbase_v1_wx_base_proto_init() {
	if File_wxbase_v1_wx_base_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_wxbase_v1_wx_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveWxMessageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveWxMessageReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxCallbackRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WxCallbackReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOpenidByCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOpenidByCodeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOfficialAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddOfficialAccountReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMiniProgramRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddMiniProgramReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOfficialAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOfficialAccountReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOfficialAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteOfficialAccountReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOfficialAccountListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOfficialAccountListReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_wxbase_v1_wx_base_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOpenidByCodeReply_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_wxbase_v1_wx_base_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_wxbase_v1_wx_base_proto_goTypes,
		DependencyIndexes: file_wxbase_v1_wx_base_proto_depIdxs,
		MessageInfos:      file_wxbase_v1_wx_base_proto_msgTypes,
	}.Build()
	File_wxbase_v1_wx_base_proto = out.File
	file_wxbase_v1_wx_base_proto_rawDesc = nil
	file_wxbase_v1_wx_base_proto_goTypes = nil
	file_wxbase_v1_wx_base_proto_depIdxs = nil
}
