// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"wx-base/internal/biz"
	"wx-base/internal/conf"
	"wx-base/internal/data"
	"wx-base/internal/server"
	"wx-base/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	officialAccountRepo := data.NewOfficialAccountRepo(dataData, logger)
	officialAccountUseCase := biz.NewOfficialAccountUseCase(officialAccountRepo, logger)
	officialAccountService := service.NewOfficialAccountService(officialAccountUseCase)
	miniProgramRepo := data.NewMiniProgramRepo(dataData, logger)
	miniProgramUseCase := biz.NewMiniProgramUseCase(miniProgramRepo, logger)
	miniProgramService := service.NewMiniProgramService(miniProgramUseCase)
	grpcServer := server.NewGRPCServer(confServer, officialAccountService, miniProgramService, logger)
	httpServer := server.NewHTTPServer(confServer, officialAccountService, miniProgramService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
