// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"wx-base/internal/biz/mini_program_biz"
	"wx-base/internal/biz/official_account_biz"
	"wx-base/internal/conf"
	"wx-base/internal/data"
	"wx-base/internal/data/mini_program_data"
	"wx-base/internal/data/offiaiacl_account_data"
	"wx-base/internal/server"
	"wx-base/internal/service/mini_program_service"
	"wx-base/internal/service/official_account_service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewGormDB(confData, logger)
	client := data.NewRedisCmd(confData, logger)
	dataData, cleanup, err := data.NewData(db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	officialAccountRepo := offiaiacl_account_data.NewOfficialAccountRepo(dataData, logger)
	officialAccountUseCase := official_account_biz.NewOfficialAccountUseCase(officialAccountRepo, logger)
	officialAccountService := official_account_service.NewOfficialAccountService(officialAccountUseCase, logger)
	miniProgramRepo := mini_program_data.NewMiniProgramRepo(dataData, logger)
	miniProgramUseCase := mini_program_biz.NewMiniProgramUseCase(miniProgramRepo, logger)
	miniProgramService := mini_program_service.NewMiniProgramService(miniProgramUseCase)
	grpcServer := server.NewGRPCServer(confServer, officialAccountService, miniProgramService, logger)
	httpServer := server.NewHTTPServer(confServer, dataData, officialAccountService, miniProgramService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
